=pod

=head1 NAME

caretaker-ssh-command - SSH forcecommand for caretaker commands

=head1 DESCRIPTION

B<caretaker-ssh-command> is designed to only execute commands required by
B<caretaker>.  This is useful if you want to use B<caretaker> with ssh on
untrusted hosts: Generate a SSH key and put it into your .ssh/authorized_keys
prefixed by C<< command="/path/to/caretaker-ssh-command" >>.  This way,
caretaker will work, but it won't be possible to gain actual SSH access to your
host.

=head1 WARNING

This is an experimental feature, security flaws may be present. Use on own risk.
