=head1 NAME

caretaker - distributed dotfile and script manager

=head1 SYNOPSIS

B<ct> [I<options>] I<action> [I<arguments>]

=head1 DESCRIPTION

B<ct> is the basic script for maintaining packages

I<action> may be one of:

=over

=item B<add> I<package>

fetch given I<package> from the package_root and install it

=item B<remove> I<package>

Remove I<package> from the local packages tree

=item B<eval> I<expression>

Evauluate I<expression>. See caretaker(7)

=item B<info> I<package>

Show information on I<package>, like dependencies, version, etc

=item B<list> [I<filter>]

List packages depending on I<filter>:

=over

=item * B<all>

show all packages

=item * B<local>

show currently installed packages (default)

=item * B<not-installed>

show remote packages which are not installed

=back

=item B<log> I<package>

Show commit history for package

=item B<push> [ I<package> ]

push new local versions to PKG_ROOT.
If no argument is given, pushes all installed packages

=item B<refresh> [ I<package> ]

Check prereqs and update symlinks of I<package>.
If no argument is given, refreshs all installed packages

=item B<status> [ I<package> ]

Check for local changes to the I<package>'s files.
If no arguments is given, checks all installed packages

=item B<update> [ B<local>|B<remote> ]

Update local/remote package list (both if no argument is given)

=item B<pull> [ I<package> ]

retrieve and install newest available version of I<package>.
If no argument is given, updates all installed packages

=back

=head2 SHORT ACTIONS

Instead of the I<action>s described above, you may also use their short
forms:

  short   long form
  -----   ---------
     a    add
     e    eval
     f    pull      (think "fetch")
     i    info
     l    log
     ls   list
     p    push
     r    refresh
     rm   remove
     s    status
     u    update

=head1 OPTIONS

Options marked as [boolean] may be negated
by prepending a 'no', like '--no-auto-update'.

Options always override the configuration file.
Also, every option refers to a configuration parameter,
so please see caretaker.conf(5) for more information.

=head1 FILES

=over

=item F<~/.caretaker.conf>

Contains configuration vars

=back

=head1 EXAMPLES

=over

=item * B<ct remote-update; ct upgrade>

Get new stuff from the packages_root.
Note: If you haven't disabled AUTOUPDATE, B<ct upgrade> will suffice here

=item * B<ct local-update; ct push>

Push local changes to the packages_root.
Note: If you haven't disabled AUTOUPDATE, B<ct push> will suffice here

=item * B<ct refresh caretaker>

'Fake-Upgrade'. Execute the appropiate commands as if the caretaker package had been
upgraded (useful when you change something but don't want to commit/push yet)

=back

=head1 AUTHOR

Daniel Friesel E<lt>derf@derf.homelinux.orgE<gt>

=head1 CREDITS

=over

=item * Lars Stoltenow (penma)

for pointing out various bugs and design mistakes

=item * Maximilian GaE<szlig> (mxey)

many ideas and suggestions

=back

=head1 SEE ALSO

L<caretaker.conf>(5), caretaker(7)
