#!/usr/bin/env zsh
## Set up a new package in the package_root
setopt err_exit
typeset package=$1
typeset -i bare=1

while [[ $1 == --* ]] {
	case $1 in
		--not-bare) bare=0
	esac
	shift
}

[[ -r ~/.caretaker.conf ]] && source ~/.caretaker.conf
[[ -d $PKG_ROOT ]] || exit 1

cd $PKG_ROOT
if [[ -d $package ]] {
	echo "Package $package already exists" >&2
	exit 2
}
mkdir $package
cd $package
if ((bare)) {
	git --bare init
} else {
	git init
	git config receive.denyCurrentBranch ignore
}

cd ${PKG_DIR-~/packages}
mkdir $package
cd $package
git init
