#!/usr/bin/env zsh

cd /${(j:/:)${(s:/:)0}[1,-4]}

for i in *(/,@); {
	if [[ -d $i/.git ]] {
		echo -n "$i git "
		echo ${$(git --git-dir=$i/.git log -n 1)[2]}
	} else {
		echo "$i: Unsupported or no repository" >&2
	}
}
