#!/usr/bin/env zsh

cd $1 || exit 100

rm -f .list

for i in *(/,@); {
	if [[ -d $i/.git ]] {
		echo -n "$i git " >> .list
		git --git-dir=$i/.git log | fgrep commit | head -n 1 | cut -d ' ' -f 2 >> .list
	} else {
		echo "Unsupported package: $i" >&2
	}
}
